<script>
	// imports
	import mapboxgl, { Popup } from 'mapbox-gl';
	import { onMount } from 'svelte';
	import { writable, get } from 'svelte/store';
	import {
		select,
		mapsource,
		maplayer,
		mapfunctions,
		mapobject,
		draw_type,
		datalayers,
		mapstyle,
		minzoom,
		maxzoom,
		location,
		maxbounds,
		level,
		zoomed
	} from './mapstore.js';

	//styling
	// import 'mapbox-gl/dist/mapbox-gl-draw.css'
	import '../css/mapbox-gl.css';

	let webgl_canvas;
	export let width = '100vw';
	export let height = '100vh';
	
	export const customselector = true;

	/// MAP creation
	async function init() {
		console.warn(webgl_canvas);
		$mapobject = new mapboxgl.Map({
			container: 'mapcontainer',
			style: mapstyle,
			minZoom: minzoom,
			maxZoom: maxzoom,
			maxBounds: maxbounds,
			pitch: 30,
			center: [0, 52],
			zoom: 4
		});
		$mapobject.addControl(
			new mapboxgl.ScaleControl({
				position: 'bottom-left'
			})
		);
		$mapobject.addControl(new mapboxgl.NavigationControl(), 'bottom-right');
		

		$mapobject.doubleClickZoom.disable();

		// correct error - ignore 403 missing tiles
		$mapobject.on('error', (e) => {
			if (e.error.status != 403) console.error(e.error.status, e.error.message);
		});

		$mapobject.on('load', SetLayers);
	}

	/// Set all Mapbox Parameters ///
	async function SetLayers() {

		mapsource.subscribe(async () => {
			// set the sources
			for (const [key, value] of Object.entries($mapsource)) {
				console.log(key, value);
				if ($mapobject.getSource(key)) $mapobject.removeSource(key);
				// if (value.hasOwnProperty('data')) value.data = await value.data; // for async loads
				$mapobject.addSource(key, value);
			}
		});

		maplayer.subscribe( () => {
			// set the layers
			for (const value of $maplayer) {
				console.log('layer',value);
				if ($mapobject.getLayer(value.id)) $mapobject.removeLayer(value.id);
				$mapobject.addLayer(value);
			}
		});

		for (const e of $mapfunctions) {
			$mapobject.off(e.event, e.layer, e.callback);
			$mapobject.on(e.event, e.layer, e.callback);
		}

		// move mapobject to location
		$mapobject.fitBounds(location.bounds, {
			padding: 20
		});

	}

	/// main
	onMount(init);
</script>

<!-- Script autogenerated by Svelte-Jinja (author: Dan Ellis) -->
<main>
	<div
		class="mapboxgl-canvas"
		tabindex="0"
		aria-label="Map"
		id="mapcontainer"
		style="width: {width}; height: {height}; "
		bind:this={webgl_canvas}
	/>


</main>

<style lang="scss">
	main {
		display: inline-block !important;
		position: relative !important;
		top: 0;
		left: 0;
		// bottom: 0;
		margin: 5px;
	}
</style>
